#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Stylised NMBS/SNCB "B in oval" mark (Henry van de Velde, 1936), embedded as
// an LVGL v9 ARGB8888 image. Generated by firmware/scripts/conv_logo.py from
// File:SNCB_logo.svg on Wikimedia Commons.
extern const lv_image_dsc_t nmbs_logo;

#ifdef __cplusplus
}
#endif
