#pragma once

// Pre-rendered HTML <option> tags for every Belgian NMBS / SNCB station,
// generated by firmware/scripts/gen_stations.py from
// https://api.irail.be/v1/stations/?format=json&lang=en
//
// Streamed by the AP-mode provisioning form (net/provision_ap.c) so the
// captive-portal datalist autocompletes against the full list without
// needing any external connectivity.

#ifdef __cplusplus
extern "C" {
#endif

extern const char STATIONS_BE_HTML_OPTIONS[];
extern const unsigned int STATIONS_BE_HTML_OPTIONS_LEN;
extern const unsigned int STATIONS_BE_COUNT;

#ifdef __cplusplus
}
#endif
