#!/usr/bin/env python3
"""Convert the upstream SNCB B-in-oval PNG into an LVGL v9 ARGB8888 image.

Output is a single self-contained C file that defines `nmbs_logo` as
`const lv_image_dsc_t` usable directly with lv_image_set_src().
"""
import argparse
import os
from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('-w', '--width',  type=int, default=56)
    ap.add_argument('-H', '--height', type=int, default=36)
    ap.add_argument('--white', action='store_true',
                    help='Recolour every non-transparent pixel to white (alpha '
                         'preserved). Useful when blitting onto a dark navy bg.')
    args = ap.parse_args()

    im = Image.open(args.src).convert('RGBA').resize(
        (args.width, args.height), Image.LANCZOS)
    w, h = im.size
    pixels = list(im.getdata())
    if args.white:
        pixels = [(255, 255, 255, a) if a > 0 else (r, g, b, a)
                  for (r, g, b, a) in pixels]

    with open(args.out, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by firmware/scripts/conv_logo.py.\n')
        f.write('// Source PNG: rasterised from File:SNCB_logo.svg on Wikimedia Commons.\n')
        f.write('// The B-in-oval (Henry van de Velde, 1936) is a registered NMBS/SNCB\n')
        f.write('// mark; it is embedded here so a device that displays NMBS train data\n')
        f.write('// can identify the operator. Do not redistribute out of context.\n\n')
        f.write('#include "lvgl.h"\n\n')
        f.write('#ifndef LV_ATTRIBUTE_MEM_ALIGN\n')
        f.write('#define LV_ATTRIBUTE_MEM_ALIGN\n')
        f.write('#endif\n\n')

        f.write('static const LV_ATTRIBUTE_MEM_ALIGN uint8_t nmbs_logo_map[] = {\n')
        # LVGL 9 ARGB8888 in-memory layout is little-endian uint32 0xAARRGGBB,
        # i.e. bytes [B, G, R, A] per pixel.
        for i, (r, g, b, a) in enumerate(pixels):
            f.write(f'0x{b:02X},0x{g:02X},0x{r:02X},0x{a:02X}, ')
            if (i + 1) % 8 == 0:
                f.write('\n')
        f.write('\n};\n\n')

        f.write('const lv_image_dsc_t nmbs_logo = {\n')
        f.write('    .header.magic  = LV_IMAGE_HEADER_MAGIC,\n')
        f.write('    .header.cf     = LV_COLOR_FORMAT_ARGB8888,\n')
        f.write(f'    .header.w      = {w},\n')
        f.write(f'    .header.h      = {h},\n')
        f.write(f'    .header.stride = {w} * 4,\n')
        f.write('    .data_size = sizeof(nmbs_logo_map),\n')
        f.write('    .data      = nmbs_logo_map,\n')
        f.write('};\n')

    bytes_total = len(pixels) * 4
    print(f'Wrote {args.out} ({w}x{h}, {bytes_total} bytes pixel data)')


if __name__ == '__main__':
    main()
