#!/usr/bin/env python3
"""Fetch the iRail station list and emit a C file with all Belgian stations
as a pre-rendered HTML `<option>` block ready to drop into the AP-mode
provisioning form.

Run this when stations are added/renamed in iRail. The generated file is
checked into git so CI builds don't need network access at compile time.

Usage:
    python firmware/scripts/gen_stations.py
"""
import argparse
import html
import json
import os
import sys
import unicodedata
import urllib.request

IRAIL_URL = (
    "https://api.irail.be/v1/stations/?format=json&lang=en"
)
USER_AGENT = (
    "moshon-timetable-build-script/0.1 "
    "(https://github.com/matsvandamme/moshon-timetable; "
    "matthieu@vmat-contracting.be)"
)


def transliterate(s: str) -> str:
    """Strip diacritics so the embedded names fit LVGL's built-in Montserrat
    font on the device side. Browsers in the captive portal don't care, but
    we want the SAME string the device will eventually display."""
    nfkd = unicodedata.normalize("NFKD", s)
    return "".join(c for c in nfkd if not unicodedata.combining(c))


def fetch_stations(url: str) -> list[dict]:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    print(f"Fetching {url} ...")
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    return data.get("station", [])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out",
        default=os.path.join("main", "stations_be.c"),
        help="Output C source file (relative to firmware/).",
    )
    ap.add_argument(
        "--url",
        default=IRAIL_URL,
        help="iRail stations endpoint.",
    )
    args = ap.parse_args()

    all_stations = fetch_stations(args.url)
    # Belgian stations only. iRail also returns some neighbouring foreign
    # stations on cross-border services; those have non-BE.NMBS ids.
    be = [s for s in all_stations if s.get("id", "").startswith("BE.NMBS.")]
    # Sort alphabetically by transliterated name so the datalist UI is
    # predictable and stable across regenerations.
    be.sort(key=lambda s: transliterate(s.get("name", "")).lower())

    print(f"  {len(be)} Belgian stations (out of {len(all_stations)} total)")

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Auto-generated by firmware/scripts/gen_stations.py.\n")
        f.write(f"// Source: {args.url}\n")
        f.write(f"// Stations: {len(be)}\n\n")
        f.write('#include "stations_be.h"\n\n')

        f.write(
            "// Pre-rendered HTML <option> tags for the AP-mode setup form's\n"
            "// datalist. Streaming this as one chunk is much cheaper than\n"
            "// looping over a string array on the device.\n"
        )
        f.write("const char STATIONS_BE_HTML_OPTIONS[] =\n")
        for s in be:
            name = transliterate(s.get("name", "")).strip()
            if not name:
                continue
            # html.escape with quote=True turns & " < > into entities so the
            # output is safe inside an HTML attribute value.
            escaped = html.escape(name, quote=True)
            f.write(f'    "<option value=\\"{escaped}\\">"\n')
        f.write("    ;\n\n")

        f.write(
            "const unsigned int STATIONS_BE_HTML_OPTIONS_LEN ="
            " sizeof(STATIONS_BE_HTML_OPTIONS) - 1;\n"
        )
        f.write(f"const unsigned int STATIONS_BE_COUNT = {len(be)};\n")

    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
